[project]
name = "llm-finetune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hong Fan Zhao", email = "hongfan.zhao@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.14.0",
    "bitsandbytes>=0.49.2",
    "datasets>=5.0.0",
    "peft>=0.19.1",
    "pillow>=12.2.0",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
    "transformers>=5.11.0",
    "trl>=1.6.0",
    "wandb>=0.27.2",
]

[project.scripts]
llm-finetune = "llm_finetune:main"

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "huggingface-hub>=1.19.0",
]

[tool.pyright]
useLibraryCodeForTypes = true

[tool.ruff.lint]
extend-select = ["I"]
